### ISSUE TITLE
以下情况LockUtils是否会失效

### ISSUE THREAD

**Issue by cnwillz** [esengine/egret-framework#14]
假设有1，2两个线程在执行
_keyX被依次设置为1，2
且他们同时通过了!getItem(this._keyY) === null检查

①假设_keyY被依次设置为1，2  
setItem(this._keyY, 1);
10毫秒后线程1即将开始resolve()
此时线程2  setItem(this._keyY, 2);
他们可能同时resolve()

②假设_keyY被依次设置为2，1
setItem(this._keyY, 2);
线程2即将开始resolve()
此时线程1 setItem(this._keyY, 1);
10毫秒后开始resolve()
他们可能同时resolve()

烦请大佬指点 谢谢

**Comment by esengine** [comment]
有代码拿出来看一下是什么样的情况吗？

我的第一个的疑惑是 typescript的多线程是怎么做到的
第二个的疑惑是 如何让两个同时通过这个检查 如果通过了那这下面的假设肯定会出问题的因为写的那些就是避免让他们同时通过才做出的策略

最后你说的这个情况我觉得最好的情况是不要让这个假设成功，判断当前锁是否被持有 如果有要等待释放后才能进行下一个回调 将锁传递给他并继续执行

**Comment by esengine** [comment]
如果有任何疑问可以再次打开这个问题
